### ISSUE TITLE
ValueError in Ti mode

### ISSUE THREAD

**Issue by niemasd** [AADavin/ZOMBI#2]
Here's my usage:

```bash
python3 Zombi.py Ti species.tre .
```

Here's the full error I received:

```
Generate events for input file species.tre
Traceback (most recent call last):
  File "Zombi.py", line 245, in <module>
    Z.T(parameters_file, experiment_folder, advanced_mode)
  File "Zombi.py", line 32, in T
    stg.events = af.generate_events(tree_file)
  File "/Users/niema/Desktop/ZOMBI/AuxiliarFunctions.py", line 208, in generate_events
    c1, c2 = node.get_children()
ValueError: too many values to unpack (expected 2)
```

Here's the contents of the species tree:

```
(1:0,2:0,3:0,4:0):1;
```

Any help would be much appreciated

**Comment by niemasd** [comment]
Ah, it seems as though perhaps Zombi doesn't support multifurcating trees?

**Comment by AADavin** [comment]
Zombi shouldn't be used with multifurcating trees. 
You are right with the root branch length disappearing in the mode Ti. I fixed that in the last commit
