### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'int' and 'str'

### ISSUE THREAD

**Issue by niemasd** [AADavin/ZOMBI#3]
I ran the following to generate the Species Tree:

```bash
python3 Zombi.py Ti species.tre output
```

where `species.tre` is the following:

```
(DUMMY:1,(((1:0,2:0):0,3:0):0,4:0):1);
```

I then ran the following to try to get a Gene Tree:

```bash
python3 Zombi.py G params.tsv output
```

where `params.tsv` is the following (tabs instead of spaces):

```
DUPLICATION 0
TRANSFER 0
LOSS 0
INVERSION 0
TRANSLOCATION 0
ORIGINATION 0
INITIAL_GENOME_SIZE 1
VERBOSE 0
```

I got the following error:

```
Traceback (most recent call last):
  File "Zombi.py", line 254, in <module>
    Z.G(parameters_file, experiment_folder, advanced_mode)
  File "Zombi.py", line 118, in G
    gss.run()
  File "/Users/niema/Desktop/ZOMBI/GenomeSimulator.py", line 271, in run
    time_to_next_genome_event = self.get_time_to_next_event(len(self.active_genomes), d, t, l, i, c, o)
  File "/Users/niema/Desktop/ZOMBI/GenomeSimulator.py", line 624, in get_time_to_next_event
    total += sum((d, t, l, i, c, o))
TypeError: unsupported operand type(s) for +: 'int' and 'str'
```

**Comment by AADavin** [comment]
Zombi does not support tree with multifurcations or 0-branch lengths! Sorry about that!
