### ISSUE TITLE
ImportError: Bio.Alphabet has been removed from Biopython.

### ISSUE THREAD

**Issue by Qiaojilim** [AADavin/Zombi#7]
hello Davin,
Thanks for your nice tool, at present I am trying to run ZOMBI. Everything works well except the last command to create output folder 'S'. There is an error about biopython import :
(please have a look when you are free, :-) )
Thanks
```
@Qiaojis-MacBook-Pro ZOMBI % python3 Zombi.py S ./Parameters/SequenceParameters.tsv ./Output_folder
Preparing simulator of sequences
Simulating sequence for gene family 63
Traceback (most recent call last):
  File "Zombi.py", line 453, in <module>
    Z.S(parameters_file, experiment_folder, advanced_mode)
  File "Zombi.py", line 238, in S
    ss.run(tree_path, sequences_folder)
  File "/Users/qiaojixu/ZOMBI/SequenceSimulator.py", line 49, in run
    evolver(seqfile=os.path.join(sequences_folder, fasta_file), ratefile=None, infofile=None, write_anc=True)
  File "/opt/anaconda3/lib/python3.8/site-packages/pyvolve/evolver.py", line 187, in __call__
    self._write_sequences(self.evolved_seqs)
  File "/opt/anaconda3/lib/python3.8/site-packages/pyvolve/evolver.py", line 257, in _write_sequences
    from Bio.Alphabet import generic_alphabet
  File "/opt/anaconda3/lib/python3.8/site-packages/Bio/Alphabet/__init__.py", line 20, in <module>
    raise ImportError(
ImportError: Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information.
```

**Comment by Qiaojilim** [comment]
I found the solution here https://biopython.org/wiki/Alphabet
thanks
